title: Loaded data into Cosmos DB with ADF
internal_name: Loaded data into Cosmos DB with ADF
vendor: azure
runtime: python3.8
memory: 128
timeout: 10
<<<<<<< HEAD
=======

>>>>>>> b8b10c83b9002d6b6b94aa589ce3390ec3fb0991
