slug: authoring-azure-cosmos-db-stored-procedures-for-multi-document-transactions 
title: Authoring Azure Cosmos DB Stored Procedures for Multi-Document Transactions
difficulty: Beginner
validation_type: Basic
